on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:
    branches:
    - main

name: main
jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [16, 18, 20]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - run: npm install

      - run: npm run lint

      - run: npm run update-index

      - run: npm run build

      - run: npm run test

      - if: matrix.node == '18' && matrix.os == 'ubuntu-latest'
        run: npm pack

      - if: matrix.node == '18' && matrix.os == 'ubuntu-latest'
        name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: imagemagick-magick-wasm
          path: ./*.tgz
